baseURL = "https://linkingmon.github.io/blog/"
languageCode = "en-us"
title = "Yu-Cheng's Notes"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowToc = true

[menu]
  [[menu.main]]
    name = "Dialog"
    url = "/Dialog/"
    weight = 1
  [[menu.main]]
    name = "LeetCode/Coding"
    url = "/coding/"
    weight = 1
  [[menu.main]]
    name = "Engineering Notes"
    url = "/note/"
    weight = 2
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 40
